name: Guitar
favicon: null
layout_spectrum: 0.2417122353799641
typography_spectrum: 0.5935506557580084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7576015496160835
  lightness: 0.7697732043452561
  saturation: 0.03811919246800244
  rhythmicContrast: 0.7166234210599214
purpose: []
